recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view
from recipes.views import records
from users.views import about_me

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name ='logout'),
    path('records/', records, name='records'),
    path('about_me/', about_me, name='about_me'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
# urls.py in the 'recipes' app
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, records
from .views import add_recipe

app_name = 'recipes'

urlpatterns = [
    path('', home, name='home'),  # Assuming you want to use 'home' as the name for the home view
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('recipes/', records, name='records'), 
    path('detail/<int:pk>/', RecipeDetailView.as_view(), name='detail'),
    path('add/', add_recipe, name='add_recipe'),
]

recipes/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Recipe(models.Model):
    difficulty_options = (
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('intermediate', 'Intermediate'),
        ('hard', 'Hard')
    )

    name = models.CharField(max_length=100)
    cooking_time = models.FloatField(help_text='in minutes')
    ingredients = models.CharField(max_length=250)
    difficulty = models.CharField(max_length=20, choices=difficulty_options, default='')
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

    @property
    def url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.FloatField(primary_key=True) 
    username =models.CharField(max_length=100)
    email = models.EmailField(max_length=254, blank=True, null=True)
    
    def __str__(self):
        return str(self.name)  

recipes/forms.py
from django import forms
from .models import Recipe

CHART__CHOICES = (          #specify choices as a tuple
   ('#1', 'Bar chart'),    # when user selects "Bar chart", it is stored as "#1"
   ('#2', 'Pie chart'),
   ('#3', 'Line chart')
   )
DIFFICULTY_CHOICES = (
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('intermediate', 'Intermediate'),
    ('hard', 'Hard'),
    ('all', 'Show All Recipes'),
)

class RecipesSearchForm(forms.Form):
    recipes_diff = forms.ChoiceField(choices= DIFFICULTY_CHOICES)
    chart_field = forms.ChoiceField(choices=CHART__CHOICES)

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'cooking_time', 'ingredients', 'difficulty', 'pic']

recipe_project/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render

def login_view(request):
    form = AuthenticationForm()
    error_message = None  # Initialize error_message with a default value

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('recipes:records')

            else:
                error_message = 'Invalid username or password'

    context = {
        'form': form,
        'error_message': error_message,
    }
    return render(request, 'auth/login.html', context)

def logout_view(request):
    logout(request) #pre-defined logout django function
    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView,DetailView
from.models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin #this libary is required to protect a class-based view
from .forms import RecipesSearchForm
import pandas as pd
from .utils import get_chart
from django.db.models import Q
from .forms import RecipeForm



# Create your views here.
 
def home(request):
    return render(request,'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')
        search_type = self.request.GET.get('search_type')

        if query:
            if search_type == 'name':
                queryset = queryset.filter(name__icontains=query)
            elif search_type == 'ingredient':
                queryset = queryset.filter(ingredients__icontains=query)
            elif search_type == 'both':
                queryset = queryset.filter(
                    Q(name__icontains=query) | Q(ingredients__icontains=query)
                )

        return queryset

class RecipeDetailView(DetailView):
   model = Recipe
   template_name = 'recipes/detail.html'
   

def records(request):
   form = RecipesSearchForm(request.POST or None)
   recipes_df = None #inztialize dataframe to none
   recipes_diff = None
   chart = None
   chart_field = None
   all_recipes = Recipe.objects.none()
    #check if button is clicked
   if request.method == 'POST' and request.POST.get('recipes_diff') == "all":
      qs=Recipe.objects.all()            # show all recipes
     

   else:
      #READ recipe_diff anc chart_type
      recipes_diff = request.POST.get('recipes_diff')
      chart_field = request.POST.get('chart_field')
      qs =Recipe.objects.filter(difficulty=recipes_diff)
   
      
   if qs:
      all_recipes=Recipe.objects.all()

      recipes_df = pd.DataFrame(qs.values())
      recipes_df['url'] = recipes_df.apply(lambda row: reverse("recipes:detail", kwargs={"pk": row["id"]}), axis=1)
      recipes_dict_list = recipes_df.to_dict(orient='records')

      #creating data for the charts
      total_recipes = all_recipes.count()
      total_recipes_dict_list = len(recipes_dict_list)

      rest_of_the_recipes= total_recipes -total_recipes_dict_list
      custom_labels = [recipes_diff, 'Other Difficulties']

      chart =get_chart(chart_field, recipes_df,total_recipes_dict_list,rest_of_the_recipes, labels=custom_labels,)


   else:
      recipes_dict_list =None
      # Pack up data to be sent to the template in the context dictionary
  
   context = {
      'form': form,
      'recipes_df': recipes_dict_list,
      'chart': chart,
   }
   return render(request, 'recipes/records.html',context)


def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recipes:list')  # Updated redirect to 'list'
    else:
        form = RecipeForm()
    return render(request, 'recipes/add_recipe.html', {'form': form})

users/views.py
from django.shortcuts import render
def about_me(request):
    return render(request, 'users/about_me.html')
# Create your views here.

recipes/templates/recipes/add_recipe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Recipe</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style_add_recipe.css' %}">
</head>
<body>
    <header>
        <h1>Add Your Favorite Recipe</h1>
    </header>
    <main>
        <form method="post">
            {% csrf_token %}
            <label for="id_name">Name:</label>
            {{ form.name }}
            <label for="id_cooking_time">Cooking Time (in minutes):</label>
            {{ form.cooking_time }}
            <label for="id_ingredients">Ingredients:</label>
            {{ form.ingredients }}
            <label for="id_difficulty">Difficulty:</label>
            {{ form.difficulty }}
            <label for="id_pic">Image:</label>
            {{ form.pic }}
            <button type="submit">Add Recipe</button>
        </form>
        <div class="links">
            <div class="home-link">
                <a href="{% url 'recipes:home' %}" style="color: #fff;text-decoration: none;">Home</a>
            </div>
            <div class="logout-link">
                <a href="{% url 'logout' %}" style="color: #fff;text-decoration: none;">Logout</a>
            </div>
        </div>
    </main>
</body>
</html>

recipes/templates/recipes/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body class="detail-page">
    <div class="container">
        <div class="content">
            <h2>Details: {{ object.name }}</h2>

            <p><b>Recipe's name:</b> {{ object.name }}</p>
            <p><b>Cooking time:</b> {{ object.cooking_time }}</p>
            <p><b>Ingredients:</b> {{ object.ingredients }}</p>
            <p><b>Difficulty:</b> {{ object.difficulty }}</p>
        </div>

        <div class="image-container">
            <img src="{{ object.pic.url }}" height="100%" class="rounded-image">
        </div>
    </div>
</body>

</html>

recipes/templates/recipes/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link rel="stylesheet" type="text/css" href="{% static 'style_list.css' %}">
</head>
<body>
    <div class="title-container green-background">
        <h1>Recipes list</h1>
    </div>
   <div class = "middle">
    <div class="search-form">
        <form method="GET" action="{% url 'recipes:list' %}">
            <input type="text" name="q" placeholder="Search...">
            <input type="radio" name="search_type" value="name"> By Name
            <input type="radio" name="search_type" value="ingredient"> By Ingredient
            <button type="submit">Search</button>
            <a href="{% url 'recipes:list' %}" style="color: #fff; text-decoration: none; " class="btn">Show All Recipes</a>
        </form>
    </div>
    <div class="links">
        
        <div class="home-link">
            <a href="{% url 'recipes:home' %}" style="color: #fff;text-decoration: none; ">Home</a>
        </div>
        <div class="logout-link">
            <a href="{% url 'logout' %}" style="color: #fff;text-decoration: none; ">Logout</a>
        </div>
    </div>
</div>
    <div class="card-container">
        {% if object_list %}
            {% for object in object_list %}
                <div class="card-hover">
                    <div class="card-hover__content">
                        <h3 class="card-hover__title">{{ object.name }}</h3>
                        <a href="{{ object.get_absolute_url }}" class="card-hover__link">
                            <span>View Recipe</span>
                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                            </svg>        
                        </a>
                    </div>
                    <div class="card-hover__extra">
                        <p class="card-hover__text">Click to view details</p>
                    </div>
                    <img src="{{ object.pic.url }}" alt="{{ object.name }}">
                </div>
            {% endfor %}
        {% else %}
            <p>No recipes found.</p>
        {% endif %}
    </div>
    
    
</body>
</html>


   

recipes/templates/recipes/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="title-container">
        <h1>Recipes list</h1>
    </div>
    <div class="logout-link">
        <a href="{% url 'logout' %}">Logout</a>
    </div>
    <table class="recipe-table">
        <tr>
            <th>Recipe's Name</th>
            <th>Recipes's Image</th>
        </tr>
        {% for object in object_list %}
        <tr>
            <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
            <td><img src="{{ object.pic.url }}" class="recipe-image"></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

recipes/templates/recipes/recipes_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Tasty Delights</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style_home.css' %}">
</head>
<body>
    <header>
        <div class="header-content">
            <h1>Welcome to Tasty Delights</h1>
            <p>Discover and share your favorite recipes with the world</p>
        </div>
    </header>

    <!-- Navigation Bar -->
    <nav>
        <a href="{% url 'login' %}">Login</a>
        <a href="/recipes/list/">Explore Recipes</a>
        <a href="{% url 'about_me' %}">About Me</a>
        <a href="{% url 'recipes:add_recipe' %}">Add Recipe</a> <!-- Link to Add Recipe page -->
    </nav>
    
    <div class="main-content">
        <div class="quote-overlay">
            <p>"The perfect meal, or the best meals, occur in a context that frequently has very little to do with the food itself"</p>
            <p>- Anthony Bourdain</p>
        </div>
        
    </div>

</body>
</html>

recipes/templates/recipes/records.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <div class="container">
        <h1 >Search for recipes difficulty</h1>

        <hr>
        <div class="links">
        <div class="logout-link">
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        <div class="home-link">
            <a href="{% url 'recipes:home' %}">Home</a>
        </div>
    </div>
        <hr>
        <div class="form-container">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Search</button>
            </form>
        </div>

        <br>

        {% if recipes_df %}
        <table border="1" cellpadding="5" cellspacing="5" class="center">
            <tr>
                <td>Recipe's Name</td>
            </tr>
            {% for object in recipes_df %}
            <tr>
                <td><a href="{{ object.url }}">{{ object.name }}</a></td>
            </tr>
            {% endfor %}
        </table>

        <br>
        <img src="data:image/png;base64, {{ chart|safe }}">
        {% else %}
        <h3>No data</h3>
        {% endif %}
    </div>
</body>
</html>

templates/users/about_me.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Me</title>
    <!-- Include a CSS file for styling -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/about_me_styles.css' %}">
</head>
<body>

<div class="about-me-container">
    <div class="about-me-left">
        <img src="{% static 'images/profile_placeholder.jpg' %}" alt="Profile Picture" class="profile-image">
    </div>
    <div class="about-me-right">
        <h2>I'm Giacomo Duca, a passionate junior web developer eager to contribute my skills to innovative projects.</h2>
        <p>With expertise in a variety of technologies, including:</p>
        <ul>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>JavaScript (ES6+)</li>
            <li>React.js</li>
            <li>Node.js</li>
            <li>Express.js</li>
            <li>Python</li>
            <li>Django</li>
            <li>RESTful APIs</li>
            <li>Git version control</li>
        </ul>
        <a href="https://tinkjimmy.github.io/Portfolio-Website/">Check some of my code here</a>
    </div>

    


</div>


</body>
</html>